### ISSUE TITLE
How to get a date?

### ISSUE THREAD

**Issue by afuno** [pulse00/monolog-parser#3]
Hi.

I have a question about a monolog-parser.

var_dump($ log ['date']); displays this:
object(DateTime)#106 (3) {
  ["date"]=>
  string(26) "2015-03-02 18:30:32.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/Moscow"
}

If you write this line:
var_dump($log['date’]->date);

It displays an error:
Notice: Undefined property: DateTime::$date in /var/www/username/data/www/site.com/path/to/file.php on line 50
NULL

How to get a date?

**Comment by pulse00** [comment]
`$log['date']` is already a `DateTime` object, so:

```php
$date = $log['date'];
echo $date->format('Y-m-d H:i:s');

```
